### ISSUE TITLE
Can't submit MailChimpSignupPage form with "Birthday" type fields

### ISSUE THREAD

**Issue by GuySartorelli** [xini/silverstripe-mailchimp-signup#10]
If a mailchimp audience has a field of the type "Birthday", the form submission gets a 400 error response: "Your merge fields were invalid".

This seems to be because of the format of the value being sent to mailchimp - birthday fields can only have a day and a month, but the datefield sends a year as well.
Adding the following line into `SignupControllerExtension::doSubscription` to debug the issue shows that changing the format of the submitted value does allow the form to submit.

```php
$mergeVars['BIRTHDAY'] = DBField::create_field('Date', $data['BIRTHDAY'])->Format('MM/dd');
```

I don't know whether it would be necessary to adjust the front-end field so a year can't be submitted, but this issue is just to resolve the error on submission.

**Comment by xini** [comment]
Thanks for this. I'll have a look into it asap.
