### ISSUE TITLE
Missing setupFormErrors causes fatal error on template

### ISSUE THREAD

**Issue by WoodrowShigeru** [xini/silverstripe-mailchimp-signup#4]
Cannot view the MailChimp Signup Form page that I've set up.

`[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'setupFormErrors' does not exist on 'SilverStripe\Forms\Form'`

The [SilverStripe 4.0.0 change log](https://docs.silverstripe.org/en/5/changelogs/4.0.0/) describes: `setupFormErrors renamed to restoreFormState`.

Which is why replacing `$form->setupFormErrors();` with `$form->restoreFormState();` in `src/Pages/SignupPageController.php` seems to solve this issue.

Are you sure this add-on is compatible with SS4?

-----

Using PHP 7.2. Excerpt from my composer.json:
```
"silverstripe/recipe-cms": "4.2.2@stable",
"innoweb/silverstripe-mailchimp-signup": "dev-master"
```

**Comment by xini** [comment]
Sorry for this, merged that in from the SS3 branch without checking...

**Comment by WoodrowShigeru** [comment]
Thanks.
